# Generated by Django 3.2.7 on 2021-09-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210906_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('post_code', models.IntegerField(null=True)),
                ('job_date', models.DateField(null=True)),
                ('job_time', models.TimeField(null=True)),
                ('job_detail', models.CharField(max_length=300)),
                ('technician', models.CharField(max_length=50, null=True)),
                ('last_service', models.DateField(null=True)),
                ('further_service', models.DateField(null=True)),
                ('service_report', models.CharField(max_length=300)),
            ],
        ),
    ]
