# Generated by Django 3.2.7 on 2021-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_job_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_record',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
