# Generated by Django 3.2.7 on 2021-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_record_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_record',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
