# Generated by Django 3.2.7 on 2021-09-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_job_record_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_record',
            name='further_service',
        ),
        migrations.RemoveField(
            model_name='job_record',
            name='last_service',
        ),
        migrations.RemoveField(
            model_name='job_record',
            name='service_report',
        ),
        migrations.CreateModel(
            name='Service_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_frequency', models.IntegerField(null=True)),
                ('Service_finished_time', models.TimeField(null=True)),
                ('further_service', models.DateField(null=True)),
                ('area_treated', models.CharField(max_length=500)),
                ('unchecked_area', models.CharField(max_length=500)),
                ('type_of_pest_control', models.CharField(max_length=100)),
                ('other_type', models.CharField(max_length=100)),
                ('service_report', models.CharField(max_length=300)),
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.job_record')),
            ],
        ),
    ]
