# Generated by Django 3.2.7 on 2021-09-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210912_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_report',
            old_name='Service_finished_time',
            new_name='service_finished_time',
        ),
    ]
