# Generated by Django 3.2.7 on 2021-09-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_service_finished_time_service_report_service_finished_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=500, null=True)),
                ('activity_date', models.DateField(null=True)),
                ('activity_time', models.TimeField(null=True)),
            ],
        ),
    ]
